#!/bin/bash

if [ -n "$TMUX" ]; then
    tmux split-window -h $EDITOR "$*"

elif [ "$TERM" = "linux" ]; then
    $EDITOR "$*"

elif [ "$TERM" = "xterm-kitty" ]; then
    echo $EDITOR "$*"
    kitty @ launch --cwd=current $EDITOR "$*"

else
    alacritty -e $EDITOR "$*" &
fi
