#!/bin/env sh

export VISUAL=$HOME/Dropbox/scripts/ewrap
export NNN_COLORS="2136"   # use a different color for each context
export NNN_TRASH=1         # trash (needs trash-cli) instead of delete

# For preview-tui
if [ $TERM = "xterm-kitty" ]; then
    export TERMIMAL="kitty"
else
    export TERMINAL="alacritty"
fi

# define bookmarks
export NNN_BMS='h:~/Dropbox/Coding/Projects/Heatflask;d:~/Downloads;c:~/Dropbox/.config;i:~/Pictures;v:~/Videos;'

# define plugins
export NNN_PLUG='p:preview-tui;c:.cbcp;v:imgview;k:pskill;'

export NNN_OPTS="EAoa"
export LC_COLLATE="C"

# Make pistol the default viewer for nnn preview-tui
#export USE_PISTOL=1

n ()
{
    # Block nesting of nnn in subshells
    if [ -n $NNNLVL ] && [ "${NNNLVL:-0}" -ge 1 ]; then
        echo "nnn is already running"
        return
    fi

    # The default behaviour is to cd on quit (nnn checks if NNN_TMPFILE is set)
    # To cd on quit only on ^G, remove the "export" as in:
    #     NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"
    # NOTE: NNN_TMPFILE is fixed, should not be modified
    NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"

    nnn -$NNN_OPTS "$@"

    if [ -f "$NNN_TMPFILE" ]; then
            . "$NNN_TMPFILE"
            rm -f "$NNN_TMPFILE" > /dev/null
    fi
}

